[package]
name = "hello_macro_derive"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
# https://github.com/dtolnay/syn
syn = "2.0.104"
# https://github.com/dtolnay/quote
quote = "1.0.40"
