[package]
name = "hello_macro_derive"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
# https://github.com/dtolnay/syn
syn = "2.0.72"
# https://github.com/dtolnay/quote
quote = "1.0.36"
