[package]
name = "chapter19"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"

[dependencies]
hello_macro = { path = "hello_macro" }
hello_macro_derive = { path = "hello_macro_derive" }

[lints.rust]
dead_code = "allow"
