name: Deny

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { os: "macos-latest", target: "x86_64-apple-darwin" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: stable
          profile: minimal
          target: ${{ matrix.platform.target }}

      # https://github.com/Swatinem/rust-cache
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: deny

      # https://github.com/EmbarkStudios/cargo-deny
      - name: Run cargo deny
        run: |
          cargo install cargo-deny
          cargo deny check
