name: Fmt

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - { os: "macos-latest", target: "x86_64-apple-darwin" }

    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions-rs/toolchain
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          override: true
          toolchain: stable
          profile: minimal
          components: rustfmt
          target: ${{ matrix.platform.target }}

      # https://github.com/Swatinem/rust-cache
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: fmt

      - name: Run cargo fmt
        run: cargo fmt --check --all
