name: Miri

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  miri:
    name: Miri
    runs-on: macos-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: miri

      # https://github.com/rust-lang/miri
      - name: Run miri
        run: cargo +nightly miri test --workspace --locked --all-targets
