name: Miri

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  miri:
    strategy:
      matrix:
        platform:
          - { os: "ubuntu-latest", target: "x86_64-unknown-linux-gnu" }
          - { os: "macos-latest", target: "x86_64-apple-darwin" }
          - { os: "windows-latest", target: "x86_64-pc-windows-msvc" }

    name: Miri
    runs-on: ${{ matrix.platform.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install miri
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: ${{ matrix.platform.target }}
          components: miri

      # https://github.com/rust-lang/miri
      - name: Run miri
        run: cargo +nightly miri test --target ${{ matrix.platform.target }} --workspace --locked --all-targets
